version: '3.7'

networks:
  exbuilder:

services:
  postgres:
    image: postgres:10
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports: 
      - "5432:5432"
    volumes:
      - ./03-database/data:/var/lib/postgres/data
      - ./03-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_DATABASE: exbuilder
      POSTGRES_USER: exbuilder
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - exbuilder
 
  adminer:
    image: adminer:4.8.0
    restart: always
    container_name: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nicu
    depends_on:
      - postgres 
    ports:
      - 8081:8080
    networks:
      - exbuilder

  jupyter:
    image: jupyter/datascience-notebook:r-4.0.3
    environment:
      - JUPYTER_TOKEN=password
    volumes:
      - ./04-analyses:/home/jovyan/work
    ports:
      - 8989:8888
    container_name: jupyter
    networks:
      - exbuilder

  rstudio:
    image: "rocker/verse:4.0.4"
    environment:
      - USERID=rstudio
      - PASSWORD=password
    volumes:
      - ./04-analyses:/home/rstudio/work
    ports:
      - 8787:8787
    container_name: rstudio
    networks:
      - exbuilder
  