version: '3.7'

networks:
  exbuilder:

services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./02-experiments:/var/www/html:delegated
    depends_on:
      - php
      - postgres
    networks:
      - exbuilder

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_RUNS_TABLE=${DB_RUNS_TABLE}
    ports:
      - "9000:9000"
    networks:
      - exbuilder

  postgres:
    image: postgres:10
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./${DATABASE_DIRECTORY}/data:/var/lib/postgresql/data
      - ./${DATABASE_DIRECTORY}/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - exbuilder
 
  adminer:
    image: adminer:4.8.0
    restart: always
    container_name: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nicu
    depends_on:
      - postgres 
    ports:
      - 8081:8080
    networks:
      - exbuilder

  jupyter:
    image: jupyter/datascience-notebook:r-4.0.3
    environment:
      - JUPYTER_TOKEN=password
      - JUPYTER_ENABLE_LAB=yes

    volumes:
      - ./${ANALYSES_DIRECTORY}:/home/jovyan/work
    ports:
      - 8989:8888
    container_name: jupyter
    networks:
      - exbuilder

  rstudio:
    image: "rocker/verse:4.0.4"
    environment:
      - USERID=rstudio
      - PASSWORD=password
    volumes:
      - ./${ANALYSES_DIRECTORY}:/home/rstudio/work
    ports:
      - 8787:8787
    container_name: rstudio
    networks:
      - exbuilder
  