version: '3.7'

networks:
  default: 
    external: 
      name: exbuilder_deployer

services:
  webserver:
    image: exbuilder/nginx:stable-alpine
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    depends_on:
      - php


  php:
    image: exbuilder/php:7.4-fpm-alpine
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_RUNS_TABLE=${DB_RUNS_TABLE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}