version: '3.7'

networks:
  default: 
    external: 
      name: exbuilder_deployer

services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./02-experiments:/var/www/html:delegated
    depends_on:
      - php


  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_RUNS_TABLE=experiments.runs
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
 
  