version: '3.7'

networks:
  default:
    external:
      - deployer

services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./02-experiments:/var/www/html:delegated
    depends_on:
      - php
      - postgres
    networks:
      - exbuilder

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_RUNS_TABLE=${DB_RUNS_TABLE}
    ports:
      - "9000:9000"
    networks:
      - exbuilder

  postgres:
    image: postgres:10
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./${DATABASE_DIRECTORY}/data:/var/lib/postgresql/data
      - ./${DATABASE_DIRECTORY}/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - exbuilder
 
  