version: '3.7'

networks:
  exbuilder:
    name: ${PROJECT_NAME}

services:
  webserver:
    image: exbuilder/nginx:stable-alpine
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    depends_on:
      - php
      - postgres
    networks:
      - exbuilder

  php:
    image: exbuilder/php:7.4-fpm-alpine
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./${EXPERIMENTS_DIRECTORY}:/var/www/html:delegated
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TABLE=${DB_TABLE}
      - DB_SSLMODE=${DB_SSLMODE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    ports:
      - "9000:9000"
    networks:
      - exbuilder

  postgres:
    image: postgres:10
    command: ["postgres", "-c", "log_statement=all"]
    container_name: ${PROJECT_NAME}_postgres
    restart: unless-stopped
    tty: true
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      # - ./${DATABASE_DIRECTORY}/data:/var/lib/postgresql/data
      - ./${DATABASE_DIRECTORY}/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - exbuilder

  jupyter:
    image: exbuilder/jupyter:r-4.0.3
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./${ANALYSES_DIRECTORY}:/home/jovyan/work
    ports:
      - 8989:8888
    container_name: ${PROJECT_NAME}_jupyter
    networks:
      - exbuilder

  rstudio:
    image: "exbuilder/rstudio:4.0.3"
    environment:
      - USERID=rstudio
      - PASSWORD=${RSTUDIO_PASSWORD}
    volumes:
      - ./${ANALYSES_DIRECTORY}:/home/rstudio/work
    ports:
      - 8787:8787
    container_name: ${PROJECT_NAME}_rstudio
    networks:
      - exbuilder
  